# Generated by Django 6.0 on 2025-12-31 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دپارتمان')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد دپارتمان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان\u200cها',
                'db_table': 'departments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='departments_code_9f933a_idx'), models.Index(fields=['is_active'], name='departments_is_acti_a777bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='موبایل است؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع تلفن',
                'verbose_name_plural': 'انواع تلفن',
                'db_table': 'phone_types',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='phone_types_code_c4b68a_idx'), models.Index(fields=['is_active'], name='phone_types_is_acti_843ea4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع سکشن',
                'verbose_name_plural': 'انواع سکشن',
                'db_table': 'section_types',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='section_typ_code_38b32d_idx'), models.Index(fields=['is_active'], name='section_typ_is_acti_c027cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سکشن')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد سکشن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='bhfphonebook.department', verbose_name='دپارتمان')),
                ('section_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='bhfphonebook.sectiontype', verbose_name='نوع سکشن')),
            ],
            options={
                'verbose_name': 'سکشن',
                'verbose_name_plural': 'سکشن\u200cها',
                'db_table': 'sections',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('personnel_code', models.CharField(max_length=20, unique=True, verbose_name='کد پرسنلی')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
                'db_table': 'staff',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['personnel_code'], name='staff_personn_5e9ff0_idx'), models.Index(fields=['national_code'], name='staff_nationa_8c518c_idx'), models.Index(fields=['is_active'], name='staff_is_acti_e9a75c_idx'), models.Index(fields=['last_name', 'first_name'], name='staff_last_na_2a33f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_current', models.BooleanField(default=True, verbose_name='فعلی')),
                ('position', models.CharField(blank=True, help_text='سمت یا نقش پرسنل در این بخش', max_length=100, null=True, verbose_name='سمت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bhfphonebook.section', verbose_name='بخش')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bhfphonebook.staff', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'انتساب پرسنل',
                'verbose_name_plural': 'انتساب\u200cهای پرسنل',
                'db_table': 'staff_assignments',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('is_primary', models.BooleanField(default=False, verbose_name='شماره اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_public', models.BooleanField(default=False, help_text='اگر فعال باشد، همه می\u200cتوانند ببینند. در غیر این صورت فقط ادمین', verbose_name='عمومی')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bhfphonebook.phonetype', verbose_name='نوع تلفن')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='bhfphonebook.staff', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'تلفن پرسنل',
                'verbose_name_plural': 'تلفن\u200cهای پرسنل',
                'db_table': 'staff_phones',
                'ordering': ['staff', '-is_primary', 'phone_type__display_order'],
            },
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(verbose_name='تاریخ جابجایی')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='دلیل جابجایی')),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='تأیید شده توسط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('from_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='bhfphonebook.section', verbose_name='از بخش')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='bhfphonebook.staff', verbose_name='پرسنل')),
                ('to_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='bhfphonebook.section', verbose_name='به بخش')),
            ],
            options={
                'verbose_name': 'تاریخچه جابجایی',
                'verbose_name_plural': 'تاریخچه جابجایی\u200cها',
                'db_table': 'transfer_history',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('is_primary', models.BooleanField(default=False, verbose_name='شماره اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.CharField(blank=True, help_text='مثلاً: منشی صبح، ایستگاه شب و...', max_length=100, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bhfphonebook.phonetype', verbose_name='نوع تلفن')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='bhfphonebook.section', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'تلفن بخش',
                'verbose_name_plural': 'تلفن\u200cهای بخش',
                'db_table': 'section_phones',
                'ordering': ['section', '-is_primary', 'phone_type__display_order'],
                'indexes': [models.Index(fields=['section', 'is_active'], name='section_pho_section_2f4451_idx'), models.Index(fields=['phone_number'], name='section_pho_phone_n_4c48fe_idx'), models.Index(fields=['is_primary'], name='section_pho_is_prim_aab81d_idx')],
                'unique_together': {('section', 'phone_number')},
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['department', 'is_active'], name='sections_departm_9754dd_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_type'], name='sections_section_2b0c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['code'], name='sections_code_d4cdf2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('department', 'name')},
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['staff', 'is_current'], name='staff_assig_staff_i_999cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['section', 'is_current'], name='staff_assig_section_c58b72_idx'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['start_date'], name='staff_assig_start_d_6ff3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['end_date'], name='staff_assig_end_dat_7c746d_idx'),
        ),
        migrations.AddIndex(
            model_name='staffphone',
            index=models.Index(fields=['staff', 'is_active'], name='staff_phone_staff_i_618d68_idx'),
        ),
        migrations.AddIndex(
            model_name='staffphone',
            index=models.Index(fields=['phone_number'], name='staff_phone_phone_n_80b9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='staffphone',
            index=models.Index(fields=['is_primary'], name='staff_phone_is_prim_d73d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='staffphone',
            index=models.Index(fields=['is_public'], name='staff_phone_is_publ_3d24d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffphone',
            unique_together={('staff', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='transferhistory',
            index=models.Index(fields=['staff', '-transfer_date'], name='transfer_hi_staff_i_a78409_idx'),
        ),
        migrations.AddIndex(
            model_name='transferhistory',
            index=models.Index(fields=['from_section'], name='transfer_hi_from_se_83330d_idx'),
        ),
        migrations.AddIndex(
            model_name='transferhistory',
            index=models.Index(fields=['to_section'], name='transfer_hi_to_sect_45e3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='transferhistory',
            index=models.Index(fields=['transfer_date'], name='transfer_hi_transfe_fc2c65_idx'),
        ),
    ]
